<a href="https://colab.research.google.com/github/Nav-ee-n/numpy-practice/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#wap to find length of each word in a given list
l=['apple','orange','mango']
l1=[]
for i in l:
  l1.append(len(i))
print(l1)

[5, 6, 5]


In [ ]:
import numpy as np

In [ ]:
l=[1,2,3,4,5]
z=np.array(l)
print(z)

l1=[1,2.0,3,4,5]
z1=np.array(l1)
z

l2=[1,2,3,"4"]
z2=np.array(l2)
z2

[1 2 3 4 5]


array(['1', '2', '3', '4'], dtype='<U21')

In [ ]:
l=[1,2,3,4,5]
z=np.array(l)
print(z)
z[-1]
z[2:]
z[-3:]
z[-1:-4:-1]
print(z[-1::-1])

[1 2 3 4 5]
[5 4 3 2 1]


In [ ]:
# scalar - 1 value
# 1 dimension - linear, vector [1,2,3]
# 2d - matrix
# 3d - tensors

In [ ]:
z.ndim      #dimension of array
z.size      #size of the array                #since its an array no need()
np.size(z)
z.shape     #no. of rows and columns

5

In [ ]:
x=np.array([[1,4],[2,5]])                     #2d
x
print(x.ndim)
print(x.shape)
print(x.size)

2
(2, 2)
4


In [ ]:
y=np.array([[[2,3],[4,5]],[[3,4],[6,7]]])   #3d
y
print(y.shape)
print(y.ndim)
print(y.size)

(2, 2, 2)
3
8


In [ ]:
#2x3
a=np.array([[1,2,4],[4,5,6]])
a
a.shape

(2, 3)

In [ ]:
#4x2
b=np.array([[1,2],[3,4],[5,6],[7,8]])
b
b.shape

(4, 2)

In [ ]:
#4x4
c=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
c
c.shape
# print(c[2,2])
# print(c[1,2:])                            # print(c[1,2],c[1,3])
# print(c[1:3,1:3])
# print(c[0:3,1:3])
# print(c[1:,1:])
# print(c[0:,0:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
#zero matrix
d=np.zeros([2,2,2],dtype=complex)
d

array([[[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]]])

In [ ]:
#one matrix
e=np.ones([2,2,2],dtype=int)
e

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [ ]:
#create two 2x2 matrix
a=np.array([[1,2],[3,4]])
a
b=np.array([[5,6],[7,8]])
b

a+b
a-b
a/b
# a*b not matrix multiplication
a@b                               # or a.dot(b)

array([[19, 22],
       [43, 50]])

In [ ]:
#full matrix
g=np.full([2,2],5)
g

array([[5, 5],
       [5, 5]])

In [ ]:
# identity matrix
# must be a square matrix and diagonal elements must be 1
h=np.eye(3)
h
# or
i=np.identity(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# 3x3
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a1
a1.shape

(3, 3)

In [ ]:
a2=a1.reshape(1,9)
a2

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
list=range(1,10)

# arange

a3=np.arange(1,20,2)
a3

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
# 5x2 without using np.array
a4=np.arange(1,11).reshape(5,2)
a4

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
# create a 3x3 matrix with float values
b=np.array([[2.3,4.5,6.7],[5.6,6.8,8.9],[56.7,45.7,34.6]])
b

array([[ 2.3,  4.5,  6.7],
       [ 5.6,  6.8,  8.9],
       [56.7, 45.7, 34.6]])

In [11]:
# floor               #perform floor division

c=np.floor(b)
c

array([[ 2.,  4.,  6.],
       [ 5.,  6.,  8.],
       [56., 45., 34.]])

In [13]:
# ceil              #reverse of floor, round off to next integer
d=np.ceil(b)
d

array([[ 3.,  5.,  7.],
       [ 6.,  7.,  9.],
       [57., 46., 35.]])

In [14]:
# round             #basic rounding off
e=np.round(b)       #rounds to closest even number in the case of .5
e

array([[ 2.,  4.,  7.],
       [ 6.,  7.,  9.],
       [57., 46., 35.]])

In [20]:
# 3x3
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

print(a.max())                      #in numpy
print(a.max(axis=1))                #axis = 1 denotes rows
print(a.max(axis=0))                #axis = 0 denotes columns

print(a.min())
print(a.min(axis=1))
print(a.min(axis=0))

print(a.sum())
print(a.sum(axis=1))
print(a.sum(axis=0))

9
[3 6 9]
[7 8 9]
1
[1 4 7]
[1 2 3]
45
[ 6 15 24]
[12 15 18]


In [21]:
np.sqrt(a)
np.sin(a)
np.cos(a)
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [22]:
# flatten                    #used to bring any matrix to 1d
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# sort
z=np.array([[2,4,3],[5,4,7],[8,4,3]])
print(np.sort(z))

print(np.sort(z,axis=0))

print(np.argsort(z,axis=1))             #used to print the index of the sorted matrix

[[2 3 4]
 [4 5 7]
 [3 4 8]]
[[2 4 3]
 [5 4 3]
 [8 4 7]]
[[0 2 1]
 [1 0 2]
 [2 1 0]]
